language: bash
dist: trusty
sudo: required

# https://github.com/manjaro/manjaro-buildbot/commit/c22c128cd5f06df54219da260892f5b4f2914a9c
group: deprecated-2017Q2

env:
  matrix:
    - INIT=openrc
  global:
    - VERBOSE_BUILD=1
    - FAIL_STRICT=1

arch:
  repos:
    - arch-openrc=http://downloads.sourceforge.net/project/archopenrc/$repo/$arch
    - arch-nosystemd=http://downloads.sourceforge.net/project/archopenrc/$repo/$arch
  packages:
    - openrc-keyring

before_install:
  - echo $TRAVIS_COMMIT_RANGE
install:
  - sudo locale-gen en_US.UTF-8

before_script:
  - ".travis/scripts/changed_packages.sh $TRAVIS_COMMIT_RANGE || travis_terminate 0"
  - .travis/scripts/setup_build_environment.sh
script:
  - ".travis/scripts/build_packages_in_chroot.sh $TRAVIS_COMMIT_RANGE"
after_script:
  - ls -1 "$HOME/manjaro-chroot/var/cache/manjaro-tools/pkg/unstable/x86_64"
  - .travis/scripts/report_build_status.sh

after_success:
  - openssl aes-256-cbc -K $encrypted_7380f730d705_key -iv $encrypted_7380f730d705_iv
    -in .travis/files/id_rsa_sf.enc -out $HOME/.ssh/id_rsa -d
  - ".travis/scripts/deploy_built_packages_in_chroot.sh"

notifications:
  email: false

# vim:set sw=2 et:
