post_install() {
	fc-cache -s > /dev/null
	mkfontscale usr/share/fonts/Type1
	mkfontdir usr/share/fonts/Type1
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install

	# if only fonts.dir and fonts.scale remain then remove them
	if  [[ $(ls -1 /usr/share/fonts/Type1/ | wc -l) -le 2 ]]; then
		if [ -f /usr/share/fonts/Type1/fonts.dir ] && [ -f /usr/share/fonts/Type1/fonts.scale ]; then
			rm -rf /usr/share/fonts/Type1
		fi
	fi
}
