#!/bin/sh
# system one time tasks

PATH=/sbin:/bin:/usr/sbin:/usr/bin

#/etc/init.d/rcS
#/etc/init.d/rmnologin

RUNLEVEL=S /usr/bin/openrc sysinit

# create the service directory and copy contents
mkdir -p /run/runit/service

# This is only needed if openrc doesn't manage agetty
#cp -R /etc/runit/init/* /run/runit/service

touch /run/runit/stopit
chmod 0 /run/runit/stopit
