#!/bin/sh

PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R6/bin

# The reason that boot is not in stage 1 is because if something hangs we can still listen for signals, however in stage 1 there are no signals
RUNLEVEL=S /usr/bin/openrc boot
RUNLEVEL=3 /usr/bin/openrc default

# not needed with openrc, this will be for pure runit
#cp -RL /etc/runit/sv/active/* /run/runit/service

exec env - PATH=$PATH \
runsvdir -P /run/runit/service 'log: ...........................................................................................................................................................................................................................................................................................................................................................................................................'
